In [1]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import StratifiedShuffleSplit,train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn import preprocessing 
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from copy import deepcopy

In [2]:
dataset = pd.read_csv("FMA_8000_with_track_and_genres.csv")

In [3]:
All_class=["Electronic","Experimental","Hip-Hop","Instrumental","Folk","International","Pop","Rock"]
class_listA=["Electronic","Experimental","Hip-Hop","Instrumental"]
class_listB=["Folk","International","Pop","Rock"]
#class_listA=["Electronic","Folk","Hip-Hop","Rock"]
#class_listB=["Instrumental","International","Experimental","Pop"]

class_listAA=class_listA[:2]
class_listAB=class_listA[2:]
class_listBA=class_listB[:2]
class_listBB=class_listB[2:]

def mask_genres(dataframe,class_list):
    new_data_frame=deepcopy(dataframe)
    mask=[x for x in All_class if x not in class_list]
    for x in mask:
        new_data_frame=new_data_frame[new_data_frame.genre!=x]
    return new_data_frame
def convert_to_class(x,class_list_A,class_list_B):
    if x in class_list_A:
        return ",".join(class_list_A)
    elif x in class_list_B:
        return ",".join(class_list_B)
    else:
        return "Invalid"
def filter_invalid(dataset,col):
    new_dataset=deepcopy(dataset)
    new_dataset=new_dataset[new_dataset[col]!="Invalid"]
    return new_dataset

In [4]:
hirerarchial_dataset=deepcopy(dataset)
hirerarchial_dataset=hirerarchial_dataset.drop("Unnamed: 0",axis=1)
hirerarchial_dataset["genre_level0"]=dataset["genre"].apply(lambda x:convert_to_class(x,class_listA,class_listB))
hirerarchial_dataset["genre_level1_A"]=dataset["genre"].apply(lambda x:convert_to_class(x,class_listAA,class_listAB))
hirerarchial_dataset["genre_level1_B"]=dataset["genre"].apply(lambda x:convert_to_class(x,class_listBA,class_listBB))
hirerarchial_dataset["genre_level2_AA"]=dataset["genre"].apply(lambda x:convert_to_class(x,[class_listAA[0]],[class_listAA[1]]))
hirerarchial_dataset["genre_level2_AB"]=dataset["genre"].apply(lambda x:convert_to_class(x,[class_listAB[0]],[class_listAB[1]]))
hirerarchial_dataset["genre_level2_BA"]=dataset["genre"].apply(lambda x:convert_to_class(x,[class_listBA[0]],[class_listBA[1]]))
hirerarchial_dataset["genre_level2_BB"]=dataset["genre"].apply(lambda x:convert_to_class(x,[class_listBB[0]],[class_listBB[1]]))
hirerarchial_dataset

0         1         2         3         4         5         6  \
0     0.424967 -0.574072 -0.205378  0.546491  1.067850  0.302817 -0.395523   
1     0.421997 -0.606361 -0.204723  0.533886  1.146231  0.277144 -0.394943   
2     0.416044 -0.580548 -0.206957  0.386746  0.951788  0.212872 -0.398086   
3     0.330282 -0.664061 -0.207915  0.303146  0.865987  0.088599 -0.400752   
4     0.261336 -0.658513 -0.208614  0.267213  0.795050  0.019048 -0.402303   
5     0.384889 -0.649945 -0.207658  0.313118  0.939155  0.155306 -0.398240   
6     0.446811 -0.610839 -0.206134  0.442822  1.021726  0.236611 -0.397075   
7     0.256236 -0.595367 -0.208178  0.273196  0.874514  0.067740 -0.402634   
8     0.204991 -0.628090 -0.209275  0.191138  0.780613 -0.001720 -0.405324   
9     0.211462 -0.625234 -0.208876  0.230424  0.841300  0.026359 -0.404091   
10    0.188672 -0.667825 -0.209534  0.236643  0.729644  0.029787 -0.405661   
11    0.217909 -0.590124 -0.208124  0.244461  0.857652  0.076071 -0.402948   
12    0.282892 -0.634539 -0.206605  0.289926  0.989891  0.139283 -0.401639   
13    0.313612 -0.617217 -0.207987  0.286112  0.874640  0.053771 -0.401860   
14    0.112902 -0.703600 -0.211092  0.171006  0.620002  0.044229 -0.410036   
15    0.216280 -0.605799 -0.207972  0.236046  0.898883  0.062560 -0.401995   
16    0.233996 -0.598878 -0.207987  0.221162  0.911457  0.049641 -0.402591   
17    0.362603 -0.603549 -0.207279  0.310885  0.958701  0.098767 -0.400478   
18    0.256375 -0.650954 -0.209610  0.198155  0.753065 -0.021031 -0.405351   
19    0.345160 -0.639557 -0.206667  0.310035  0.998207  0.128108 -0.398813   
20    0.399652 -0.612987 -0.205770  0.448837  1.058676  0.233474 -0.395348   
21    0.346907 -0.661367 -0.207428  0.354903  0.890011  0.108882 -0.400075   
22    0.367396 -0.607169 -0.206943  0.366563  0.954764  0.162975 -0.397774   
23    0.387283 -0.625143 -0.207618  0.344873  0.865453  0.090869 -0.400009   
24    0.293016 -0.691877 -0.208384  0.272911  0.809457  0.054296 -0.400682   
25    0.363288 -0.642063 -0.207254  0.326290  0.931718  0.120553 -0.399521   
26    0.399181 -0.650666 -0.207358  0.335690  0.895526  0.132182 -0.399397   
27    0.427287 -0.614612 -0.205967  0.439204  1.063197  0.261411 -0.395705   
28    0.245573 -0.690527 -0.209977  0.197469  0.714692 -0.022710 -0.404578   
29    0.095638 -0.731329 -0.211464  0.066770  0.616344 -0.127750 -0.410165   
...        ...       ...       ...       ...       ...       ...       ...   
7970  0.384095 -0.600357 -0.207270  0.354679  0.927522  0.162633 -0.400650   
7971  0.306273 -0.610447 -0.208520  0.310790  0.805840  0.097597 -0.401014   
7972  0.320546 -0.612081 -0.207354  0.342766  0.887149  0.148036 -0.400065   
7973  0.451562 -0.627732 -0.206577  0.398509  1.010792  0.269015 -0.398352   
7974  0.382934 -0.603442 -0.206519  0.379279  0.992512  0.226063 -0.398463   
7975  0.481494 -0.598004 -0.205311  0.451647  1.036266  0.281001 -0.397693   
7976  0.381655 -0.624786 -0.206381  0.373222  1.045305  0.172838 -0.397396   
7977  0.393162 -0.574776 -0.205951  0.401951  1.063783  0.246755 -0.397086   
7978  0.337083 -0.592311 -0.206156  0.409459  1.013213  0.203443 -0.398169   
7979  0.342746 -0.623578 -0.207419  0.283589  0.904622  0.110719 -0.401280   
7980  0.381132 -0.598886 -0.204944  0.501065  1.150936  0.231375 -0.396647   
7981  0.346792 -0.588940 -0.206023  0.409604  1.042186  0.231466 -0.398571   
7982  0.310298 -0.651767 -0.207547  0.322990  0.896653  0.151799 -0.400184   
7983  0.278010 -0.664577 -0.209649  0.208357  0.762958 -0.000864 -0.404394   
7984  0.323796 -0.611904 -0.208449  0.254191  0.869808  0.065655 -0.403058   
7985  0.444748 -0.623029 -0.205408  0.476981  1.038385  0.289388 -0.397141   
7986  0.447866 -0.593734 -0.205846  0.467539  1.054951  0.239039 -0.396677   
7987  0.370936 -0.583844 -0.207190  0.329025  0.942468  0.154515 -0.400012   
7988  0.301369 -0.614408 -0.206890  0.321266  0.938038  0.118936 -0.400600   
7989  0.382519 -0.629622 -0.207065 

Level 0:-

In [5]:
test_size=.30
cols=hirerarchial_dataset.iloc[:,160:].columns
features=hirerarchial_dataset.drop(cols,axis=1).as_matrix()     #removing track_id(Unnamed: 0) and genre in the dataset and converting to numpy array
lables=hirerarchial_dataset.genre_level0.as_matrix()
scaled_features=preprocessing.scale(features)
scaled_features.shape

(8000, 160)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features, lables,test_size=test_size, random_state=42,stratify=lables)

In [7]:
svm_model_level0=svm.SVC(C=2)
svm_model_level0.fit(X_train,y_train)
print("Svm statistics :-")
print("Training accuracy : ",accuracy_score(y_train,svm_model_level0.predict(X_train)))
print("Testing accuracy : ",accuracy_score(y_test,svm_model_level0.predict(X_test)))
print("Confusion metrics for testing :-\n",confusion_matrix(y_test,svm_model_level0.predict(X_test),labels=svm_model_level0.classes_))
print("Genres considered : "," and ".join(svm_model_level0.classes_))

Svm statistics :-
Training accuracy :  0.939107142857
Testing accuracy :  0.821666666667
Confusion metrics for testing :-
 [[996 204]
 [224 976]]
Genres considered :  Electronic,Experimental,Hip-Hop,Instrumental and Folk,International,Pop,Rock


Level 1:-

In [8]:
cols=hirerarchial_dataset.iloc[:,160:].columns
level1A=filter_invalid(hirerarchial_dataset,"genre_level1_A")
features=level1A.drop(cols,axis=1).as_matrix()     #removing track_id(Unnamed: 0) and genre in the dataset and converting to numpy array
lables=level1A.genre_level1_A.as_matrix()
scaled_features=preprocessing.scale(features)
scaled_features.shape

(4000, 160)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features, lables, test_size=test_size, random_state=42,stratify=lables)

In [10]:
svm_model_level1A=svm.SVC(C=2)
svm_model_level1A.fit(X_train,y_train)
print("Svm statistics :-")
print("Training accuracy : ",accuracy_score(y_train,svm_model_level1A.predict(X_train)))
print("Testing accuracy : ",accuracy_score(y_test,svm_model_level1A.predict(X_test)))
print("Confusion metrics for testing :-\n",confusion_matrix(y_test,svm_model_level1A.predict(X_test),labels=svm_model_level1A.classes_))
print("Genres considered : "," and ".join(svm_model_level1A.classes_))

Svm statistics :-
Training accuracy :  0.948571428571
Testing accuracy :  0.771666666667
Confusion metrics for testing :-
 [[458 142]
 [132 468]]
Genres considered :  Electronic,Experimental and Hip-Hop,Instrumental


In [11]:
cols=hirerarchial_dataset.iloc[:,160:].columns
level1B=filter_invalid(hirerarchial_dataset,"genre_level1_B")
features=level1B.drop(cols,axis=1).as_matrix()     #removing track_id(Unnamed: 0) and genre in the dataset and converting to numpy array
lables=level1B.genre_level1_B.as_matrix()
scaled_features=preprocessing.scale(features)
scaled_features.shape

(4000, 160)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features, lables, test_size=test_size, random_state=42,stratify=lables)

In [13]:
svm_model_level1B=svm.SVC(C=2)
svm_model_level1B.fit(X_train,y_train)
print("Svm statistics :-")
print("Training accuracy : ",accuracy_score(y_train,svm_model_level1B.predict(X_train)))
print("Testing accuracy : ",accuracy_score(y_test,svm_model_level1B.predict(X_test)))
print("Confusion metrics for testing :-\n",confusion_matrix(y_test,svm_model_level1B.predict(X_test),labels=svm_model_level1B.classes_))
print("Genres considered : "," and ".join(svm_model_level1B.classes_))

Svm statistics :-
Training accuracy :  0.956428571429
Testing accuracy :  0.8225
Confusion metrics for testing :-
 [[492 108]
 [105 495]]
Genres considered :  Folk,International and Pop,Rock


level 2:-

In [14]:
cols=hirerarchial_dataset.iloc[:,160:].columns
level2AA=filter_invalid(hirerarchial_dataset,"genre_level2_AA")
features=level2AA.drop(cols,axis=1).as_matrix()     #removing track_id(Unnamed: 0) and genre in the dataset and converting to numpy array
lables=level2AA.genre_level2_AA.as_matrix()
scaled_features=preprocessing.scale(features)
scaled_features.shape

(2000, 160)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features, lables, test_size=test_size, random_state=42,stratify=lables)

In [16]:
svm_model_level2AA=svm.SVC(C=2)
svm_model_level2AA.fit(X_train,y_train)
print("Svm statistics :-")
print("Training accuracy : ",accuracy_score(y_train,svm_model_level2AA.predict(X_train)))
print("Testing accuracy : ",accuracy_score(y_test,svm_model_level2AA.predict(X_test)))
print("Confusion metrics for testing :-\n",confusion_matrix(y_test,svm_model_level2AA.predict(X_test),labels=svm_model_level2AA.classes_))
print("Genres considered : "," and ".join(svm_model_level2AA.classes_))

Svm statistics :-
Training accuracy :  0.977142857143
Testing accuracy :  0.858333333333
Confusion metrics for testing :-
 [[257  43]
 [ 42 258]]
Genres considered :  Electronic and Experimental


In [17]:
cols=hirerarchial_dataset.iloc[:,160:].columns
level2AB=filter_invalid(hirerarchial_dataset,"genre_level2_AB")
features=level2AB.drop(cols,axis=1).as_matrix()     #removing track_id(Unnamed: 0) and genre in the dataset and converting to numpy array
lables=level2AB.genre_level2_AB.as_matrix()
scaled_features=preprocessing.scale(features)
scaled_features.shape

(2000, 160)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features, lables, test_size=test_size, random_state=42,stratify=lables)

In [19]:
svm_model_level2AB=svm.SVC(C=2)
svm_model_level2AB.fit(X_train,y_train)
print("Svm statistics :-")
print("Training accuracy : ",accuracy_score(y_train,svm_model_level2AB.predict(X_train)))
print("Testing accuracy : ",accuracy_score(y_test,svm_model_level2AB.predict(X_test)))
print("Confusion metrics for testing :-\n",confusion_matrix(y_test,svm_model_level2AB.predict(X_test),labels=svm_model_level2AB.classes_))
print("Genres considered : "," and ".join(svm_model_level2AB.classes_))

Svm statistics :-
Training accuracy :  0.992857142857
Testing accuracy :  0.918333333333
Confusion metrics for testing :-
 [[278  22]
 [ 27 273]]
Genres considered :  Hip-Hop and Instrumental


In [20]:
cols=hirerarchial_dataset.iloc[:,160:].columns
level2BA=filter_invalid(hirerarchial_dataset,"genre_level2_BA")
features=level2BA.drop(cols,axis=1).as_matrix()     #removing track_id(Unnamed: 0) and genre in the dataset and converting to numpy array
lables=level2BA.genre_level2_BA.as_matrix()
scaled_features=preprocessing.scale(features)
scaled_features.shape

(2000, 160)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features, lables, test_size=test_size, random_state=42,stratify=lables)

In [22]:
svm_model_level2BA=svm.SVC(C=2)
svm_model_level2BA.fit(X_train,y_train)
print("Svm statistics :-")
print("Training accuracy : ",accuracy_score(y_train,svm_model_level2BA.predict(X_train)))
print("Testing accuracy : ",accuracy_score(y_test,svm_model_level2BA.predict(X_test)))
print("Confusion metrics for testing :-\n",confusion_matrix(y_test,svm_model_level2BA.predict(X_test),labels=svm_model_level2BA.classes_))
print("Genres considered : "," and ".join(svm_model_level2BA.classes_))

Svm statistics :-
Training accuracy :  0.98
Testing accuracy :  0.856666666667
Confusion metrics for testing :-
 [[254  46]
 [ 40 260]]
Genres considered :  Folk and International


In [23]:
cols=hirerarchial_dataset.iloc[:,160:].columns
level2BB=filter_invalid(hirerarchial_dataset,"genre_level2_BB")
features=level2BB.drop(cols,axis=1).as_matrix()     #removing track_id(Unnamed: 0) and genre in the dataset and converting to numpy array
lables=level2BB.genre_level2_BB.as_matrix()
scaled_features=preprocessing.scale(features)
scaled_features.shape

(2000, 160)

In [24]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features, lables, test_size=test_size, random_state=42,stratify=lables)

In [25]:
svm_model_level2BB=svm.SVC(C=2)
svm_model_level2BB.fit(X_train,y_train)
print("Svm statistics :-")
print("Training accuracy : ",accuracy_score(y_train,svm_model_level2BB.predict(X_train)))
print("Testing accuracy : ",accuracy_score(y_test,svm_model_level2BB.predict(X_test)))
print("Confusion metrics for testing :-\n",confusion_matrix(y_test,svm_model_level2BB.predict(X_test),labels=svm_model_level2BB.classes_))
print("Genres considered : "," and ".join(svm_model_level2BB.classes_))

Svm statistics :-
Training accuracy :  0.957142857143
Testing accuracy :  0.768333333333
Confusion metrics for testing :-
 [[235  65]
 [ 74 226]]
Genres considered :  Pop and Rock


Ensemble Logic:-

In [26]:
def ensemble_predict(y):
    level0_predict=svm_model_level0.predict(y)
    classA,classB=svm_model_level0.classes_
    for level0_class in level0_predict:
        if level0_class==classA:
            level1_predict=svm_model_level1A.predict(y)
            classAA,classAB=svm_model_level1A.classes_
            for level1_class in level1_predict:
                if level1_class==classAA:
                    level2_predict=svm_model_level2AA.predict(y)
                else:
                    level2_predict=svm_model_level2AB.predict(y)              
        else:
            level1_predict=svm_model_level1B.predict(y)
            classBA,classBB=svm_model_level1B.classes_
            for level1_class in level1_predict:
                if level1_class==classBA:
                    level2_predict=svm_model_level2BA.predict(y)
                else:
                    level2_predict=svm_model_level2BB.predict(y)
    return level2_predict
def Ensemble_model_predictions(Y):
    predictions=[]
    for y in Y:
        predictions.extend(ensemble_predict([y]))
    return predictions

Finally:-

In [27]:
cols=hirerarchial_dataset.iloc[:,160:].columns
base_level=filter_invalid(hirerarchial_dataset,"genre")
features=base_level.drop(cols,axis=1).as_matrix()     
lables=base_level.genre.as_matrix()
scaled_features=preprocessing.scale(features)
scaled_features.shape

(8000, 160)

In [28]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features, lables, test_size=test_size, random_state=42,stratify=lables)

In [29]:
print("Ensemble statistics :-")
print("Training accuracy : ",accuracy_score(y_train,Ensemble_model_predictions(X_train)))
print("Testing accuracy : ",accuracy_score(y_test,Ensemble_model_predictions(X_test)))
print("Confusion metrics for testing :-\n",confusion_matrix(y_test,Ensemble_model_predictions(X_test),labels=All_class))
print("Genres considered : ",",".join(All_class))

Ensemble statistics :-
Training accuracy :  0.768571428571
Testing accuracy :  0.747083333333
Confusion metrics for testing :-
 [[243  22   8  13   4   2   4   4]
 [ 38 176   7  17  17  12   9  24]
 [ 23   6 251   8   2   1   7   2]
 [ 19  14   6 233   9   2   1  16]
 [  0   4   1  18 250  12   4  11]
 [ 16   2   5   1  16 245   4  11]
 [ 16   9  11   7  33  21 146  57]
 [  4   8   4   5  11   5  14 249]]
Genres considered :  Electronic,Experimental,Hip-Hop,Instrumental,Folk,International,Pop,Rock


In [ ]:
from sklearn.externals import joblib
joblib.dump(svm_model_level0, "svm_model_level0")
joblib.dump(svm_model_level1A,"svm_model_level1A")
joblib.dump(svm_model_level1B, "svm_model_level1B")
joblib.dump(svm_model_level2AA, "svm_model_level2AA")
joblib.dump(svm_model_level2AB, "svm_model_level2AB")
joblib.dump(svm_model_level2BA, "svm_model_level2BA")
joblib.dump(svm_model_level2BB, "svm_model_level2BB")